# Site settings
title: Tatubola
header-img: img/home-bg.jpg
email: tatubolapodcast@gmail.com
description: "Tatubola é um podcast para voce que quer sair do buraco, sempre sabemos como vai comecar mas nunca como vai terminar!"
baseurl: ""
url: "http://tatubola.net"
twitter_username: tatubolapodcast
#github_username: italoclone
facebook_username: tatubolapodcast

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
