# Site settings
title: Tatubola
header-img: img/home-bg.jpg
email: tatubolapodcast@gmail.com
description: "Tatubola é um podcast para voce que quer sair do buraco, sempre sabemos como vai comecar mas nunca como vai terminar!"
baseurl: ""
url: "http://tatubola.net"
twitter_username: tatubolapodcast
#github_username: italoclone
facebook_username: tatubolapodcast
soundcloud_username: tatubola
link_itunes: https://geo.itunes.apple.com/br/podcast/tatubola/id1008227182?mt=2&uo=6
link_android: http://subscribeonandroid.com/feeds.soundcloud.com/users/soundcloud:users:151170013/sounds.rss

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
